# Generated by Django 2.1.7 on 2019-03-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190311_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameModel(
            old_name='Catagory',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='url',
            new_name='book_url',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='catagory',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='catagory',
            new_name='category',
        ),
    ]
    
    atomic = False
    