# Generated by Django 2.1.7 on 2019-03-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_book_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('SCF', 'Science Fiction'), ('PRG', 'Programming'), ('FEM', 'Feminism'), ('POL', 'Politics'), ('HUM', 'Humor'), ('HOR', 'Horror')], default=None, max_length=10),
        ),
    ]
