# Generated by Django 2.1.7 on 2019-03-13 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190312_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='date_added',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
