# Generated by Django 2.1.7 on 2019-03-15 19:51
import os.path, csv
from django.conf import settings
from django.core.files import File
from django.db import migrations
from django.utils.text import slugify

def get_book_csv(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20190315_1444'),
    ]

    operations = [
        migrations.RunPython(get_book_csv)
    ]
